### ISSUE TITLE
Não foi encontrada configuração de assinatura informada. Não é possível continuar.

### ISSUE THREAD

**Issue by DanielMaceira** [san0suke/pagseguro-assinaturas-rcs#1]
Olá amigo! Pretendo contribuir contigo, porém estou tendo dificuldade na implantação. Fiz toda a configuração do Plugin como informado, entrei no pagseguro e criei os planos de assinatura. Porém ao finalizar o pedido, quando é redirecionado ao pagseguro, recebo a mensagem:

> **Não foi encontrada configuração de assinatura informada. Não é possível continuar.**

Sabe me orientar? Agradeço desde já!
Assim que concluir o funcionamento, mando uma ajuda à você ;)

**Comment by san0suke** [comment]
Não há a necessidade de criar os planos no Pagseguro. Cada nova inscrição acaba sendo uma assinatura...
Isso já aconteceu comigo uma vez, vou verificar o que era.

**Comment by san0suke** [comment]
Verifique se o token e email informados são do ambiente escolhido.
Nas configurações do plugin, existem os campos:

* Token de acesso	
* Email do Pagseguro
* Pagseguro Assinaturas sandbox	(on/off)

Se não me engano isso pode ocorrer se você informou o token de Sandbox, mas o sandbox está desativado, e o contrário também. ( se você informou o token de produção mas está marcado como modo sandbox)

**Comment by hodneyf** [comment]
Olá, estou fazendo teses com o seu plugin e me deparei com o problema acima. 
O erro se passa tanto no SendBox, quanto na utilização da conta real do PagSeguro... 
Tentei gerar novos tokens, e utilizar outras contas pagseguro mas o problema permanece, você tem ideia do que possa ser?

Desde já agradeço!

**Comment by san0suke** [comment]
Entre em https://sandbox.pagseguro.uol.com.br/vendedor/configuracoes.html
 E obtenha seu token e email.

Após isto vá até sua tela de configuração do checkout e marque o campo:
Pagseguro Assinaturas sandbox -> on

Isto vai fazer funcionar no modo sandbox
Se não resolver avise.

**Comment by hodneyf** [comment]
Olá de novo...
Instalei e fiz os testes e tudo funcionou corretamente! :-) 
O erro que tinha comentada antes era referente ao preço do produto, meu produto estava com o valor de R$ 0,01, quando chegava o uol o mesmo mostrava a mensagem:
Não foi encontrada configuração de assinatura informada. Não é possível continuar.
Alterei o valor do produto e a integração funcionou corretamente.

Parabéns pelo trabalho e esforço, não encontrei nada parecido e sei que o seu produto fará sucesso.
No meu caso estamos fazendo a recorrência para planos de exercícios em uma academia de Yoga, Pilates e etc..., ou seja não é produto digital mas serviço físico e o seu plugin serviu muito bem.  

Abraço!
