### ISSUE TITLE
Undefined index: _intervalo_ciclo_plano 

### ISSUE THREAD

**Issue by DanielOizumi** [san0suke/pagseguro-assinaturas-rcs#11]
Boa tarde!
Estou recebendo esse erro no produto, carrinho e no finalizar-compra.
Notice: Undefined index: _intervalo_ciclo_plano in /pagseguro-assinaturas-rcs/PGA_Compra.class.php on line 254
Observando o PGA_Planos.class.php não encontro o campo de intervalo na função add_campos_plano, seria esse o problema?
Estou com dúvidas de onde vem o valor do intervalo do plano. Acho que deveria ser estabelecido dentro das configurações do produto, no entanto não encontro nada relacionado.
Muito obrigado pela sua atenção,
Daniel.

**Comment by san0suke** [comment]
Coloca um @ , arroba na frente de onde tiver $produto_meta['_intervalo_ciclo_plano'][0] e commita fazendo o favor.

**Comment by san0suke** [comment]
@$produto_meta['_intervalo_ciclo_plano'][0]

**Comment by san0suke** [comment]
Isso é um campo que eu acredito que será feito no futuro neh...

**Comment by DanielOizumi** [comment]
Entendi!!!
Show! Obrigado pela ajuda.

**Comment by DanielOizumi** [comment]
Se conseguir um tempo eu tento implementar essa função de estabelecer o ciclo.
Abraços!
