### ISSUE TITLE
Não foi encontrada configuração de assinatura informada. Não é possível continuar.

### ISSUE THREAD

**Issue by jonasrafael** [san0suke/pagseguro-assinaturas-rcs#13]
O erro acima aparece no checkout....

- Como vincula o plano cadastrado no woo com o plano no painel woocommerce?

Link: https://pagseguro.uol.com.br/pagamento-recorrente/planos/lista.jhtml

**Comment by san0suke** [comment]
Toda vez que alguém faz uma assinatura, um novo plano é criado com o valor da compra e a vinculação é feita automaticamente. Este erro pode ser:
- A chave utilizada é de sandbox, mas o ambiente de produção está habilitado.
- A chave utilizada é de produção, mas o ambiente de sandbox está habilitado.
- O valor do produto é muito baixo e não pode ser processado.
- Token digitado é inválido.

Verifique se não é nada disso.

**Comment by sharuto** [comment]
Oi. Tambem estou com este problema. Já chequei as configurações e sempre que sou redirecionado para o pagseguro aparece esta mensagem de "Não foi encontrada configuração de assinatura informada. Não é possível continuar."

O site é https://www.academiadovendedor.com.br/

Você faz idéia do que pode ser? Você faria um freela pra resolver este problema?

Abs

**Comment by jonasrafael** [comment]
Tentei e não deu boa, tentei criar também os nomes dos planos pra ver se eram case-sensitive. Nada :(

**Comment by jonasrafael** [comment]
Quer testar conosco Robson?

**Comment by san0suke** [comment]
Pra resolver isto eu teria que ter um ambiente pra isto com total acesso.
Se você quiser montar um ambiente pra eu dar uma olhada...
Vou precisar dos acessos:
FTP, Login e senha do wp admin, login e senha da conta do pag seguro.

Eu também não sei como vc vai me passar isso. O git tem algum meio de comunicação direto?

**Comment by san0suke** [comment]
Se conseguir me passar isso de alguma forma, eu entro e resolvo seu problema.

**Comment by jonasrafael** [comment]
Vou preparar isso e te passo agora no começo da tarde.

**Comment by jonasrafael** [comment]
Preciso te passar esses dados em um inbox ou algo assim, onde é melhor? Face, gtalk, whats?

**Comment by san0suke** [comment]
Pode enviar em:
san0sukeX.X.X.X.X@gmail.com

**Comment by jonasrafael** [comment]
Salve mano, acabei não enviando pois conseguimos resolver aqui;


Algumas coisas que configuramos durante o teste até pra você colocar no README;

- Verificar o link do url de retorno ela mostra http e deveria ser https;
(Quando coloquei https não deu, quando coloquei http deu boa;
Note que vai ser descontinuado/atualizado; https://pagseguro.uol.com.br/preferences/automaticReturn.jhtml )
- Remover dados de sandbox do pagseguro; Deixar só o live;

**Comment by san0suke** [comment]
Tendi nada, faz o favor explica e põe no README que eu adiciono seu pull request.
