### ISSUE TITLE
Woocommerce Subscriptions

### ISSUE THREAD

**Issue by jonasrafael** [san0suke/pagseguro-assinaturas-rcs#14]
Seria legal usar esse plugin com Woocommmerce Subscriptions, ele facilita pra controlar os sistemas de assinatura dentro do painel e os relatórios do painel também. Dá uma olhada:

https://docs.woocommerce.com/document/subscriptions/

O plugin de assinatura do Stripe tem uma forma bem similar e que funciona bem, mas tem algumas limitaçõeszinhas.

**Comment by san0suke** [comment]
Favor implementar e realizar um pull request com os novos recursos.
