### ISSUE TITLE
Pagamento Recorrente / Assinatura por Créditos e Não por Períodos

### ISSUE THREAD

**Issue by midiamatic** [san0suke/pagseguro-assinaturas-rcs#2]
Existe alguma solução para configurar produtos com créditos?

O cliente poderia comprar pacotes de créditos (10, 20, 30, etc) e a cada utilização seria debitado 1 crédito do seu pacote. Que poderia ter uma validade (30, 45, 60 dias).

Durante a validade, ele poderia utilizar os créditos através da sua área de cliente. A cada utilização, um crédito seria debitado. Até zerar. Aí ele compraria mais créditos. 

Seria como um telefone pré-pago.

**Comment by san0suke** [comment]
O Pagseguro possui parâmetros que podem ser enviados tanto de limite de tempo, quanto de limite de valor.
Basta que este recurso seja adicionado no plugin.
Gostaria de se tornar um contribuinte do projeto?

**Comment by midiamatic** [comment]
Mas o principal não é o limite de tempo, nem tampouco o valor. A questão principal são os créditos.

É um serviço de consulta. O cliente irá comprar por exemplo 10 créditos (válidos por 45 dias). Nesse período, ele irá utilizar os seus créditos. Cada crédito corresponde a uma consulta. Então, ele pode usar um crédito hoje, 3 amanhã, mais 2 na semana que vem, etc. Até consumir os créditos. 

Consumidos todos eles, ele precisará comprar mais para pedir mais consultas.

Esse sistema de controle de créditos deverá ser automático.

**Comment by san0suke** [comment]
Não é assim que o plugin funciona.

O plugin é apenas um gateway de pagamento para pagamentos repetitivos em períodos

**Comment by midiamatic** [comment]
Imaginei. Por isso perguntei.
