### ISSUE TITLE
Fatal erro

### ISSUE THREAD

**Issue by Iuguernaut** [san0suke/pagseguro-assinaturas-rcs#20]
Instalei o plugin, daí quando vou em woocommerce>configurações>finalizar compra aparece o seguinte erro:
Fatal error: Call to a member function get_cart() on null in /home/vivaarte/public_html/wp-content/plugins/pagseguro-assinaturas-rcs-master/PGA_Compra.class.php on line 64

**Comment by san0suke** [comment]
Não coloque o plugin na pasta pagseguro-assinaturas-rcs-master
Use pagseguro-assinaturas-rcs

**Comment by Iuguernaut** [comment]
Realmente veio com o master no final, mas alterei e continuou com o mesmo problema. Baixei o plugin, abrir o arquivo compactado, renomeei a pasta e instalei o plugin. Continuou com o erro.

**Comment by san0suke** [comment]
Troque a linha 64 do arquivo PGA_Compra.class.php
de:
`$itens = WC()->cart->get_cart();`
Por:
`global $woocommerce;
    $items = $woocommerce->cart->get_cart();`

E me avise pra eu saber se funcionou.

**Comment by Iuguernaut** [comment]
Fiz a alteração e o problema continua. Outro problema que também está dando, mesmo antes da alteração, é que ao acessar a página de assinaturas dentro do woocommerce, as assinaturas não aparecem(tenho o woocommerce subscription instalado)

**Comment by erloncharlesbf** [comment]
Esse plugin não funciona em conjunto com o woocommerce subscription.
Sempre q os dois estão juntos algumas configurações do woocommerce somem, na verdade não é necessário usar o subscription, só o assinaturas e o membership
