### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by erloncharlesbf** [san0suke/pagseguro-assinaturas-rcs#21]
A criação de assinaturas está funcionando perfeitamente.
Quando o pagseguro tenta envar uma notificação para `http://meusite.com.br/?wc-api=PGA_Gateway` está retornando **301 Moved Permanently**.

**Comment by san0suke** [comment]
meusite seria no caso seu site né?
Confirme na documentação da sua versão do woocommerce qual a url correta para acessar este gateway

**Comment by erloncharlesbf** [comment]
Segundo a [API](https://docs.woocommerce.com/document/wc_api-the-woocommerce-api-callback/) a URL deveria ser `http://meusite.com.br/wc-api/PGA_Gateway`. 
Seria interresante trocar isso no PGA_Utils.class.php na linha 66, para evitar uma recomendação de URL de notificação errada

**Comment by san0suke** [comment]
Se você puder fazer isto, e em seguida mandar um pull request, eu agradeço.
