### ISSUE TITLE
Retorno de Pagamento Aprovado (não funciona)

### ISSUE THREAD

**Issue by daniloferweb** [san0suke/pagseguro-assinaturas-rcs#25]
Olá tudo bem?

Primeiramente parabéns pelo plugin, está funcionando conforme nossas expectativas, o único detalhe é que após o cliente finalizar a compra, e ela processar como CONCLUÍDO, esse processamento não retorna para nossa loja. Fiz os testes até mesmo no SANDBOX, e esse notificação não chega.

Dessa forma não consigo identificar o Pagamento sem precisar ir até o Pagseguro.

Obrigado!

**Comment by san0suke** [comment]
É preciso configurar as URLs de notificação no Pagseguro.
Obs.: faz muito tempo que eu desenvolvi esse plugin pode ser que não esteja funcionando nas versões atuais do wordpress.

**Comment by daniloferweb** [comment]
Eu configurei sim... elas estão funcionando... analisando mais a fundo agora etapa por etapa. Ele nunca chegará ao Status de Concluído, pois ele é uma cobrança recorrente, após efetuar o primeiro pagamento, ele já gera um Processamento para o próximo mês.

Estou certo?

**Comment by san0suke** [comment]
Ele só conclui a venda no seu site quando a assinatura no pagseguro for cancelada  ou o usuário deixar de pagar.

**Comment by daniloferweb** [comment]
Show de bola! Muito obrigado!
Parabéns pelo trabalho!

Se tiver algum contato de e-mail ou whatsapp, gostei do seu trabalho!
