### ISSUE TITLE
Doação e Novas Funcionalidades

### ISSUE THREAD

**Issue by petrusdemelo** [san0suke/pagseguro-assinaturas-rcs#3]
Amigo, para implementar a função de checkout transparente e ao invés de criar um novo plano, fazer a adesão de um plano existente, levaria quanto tempo de você?

Você tem uma ideia de quanto poderíamos doar para você desenvolver essas funcionalidades?

Fiz um fork aqui do seu projeto mas a verdade é que sei muito pouco ainda de php, wordpress e woocommerce pra criar algo decente.

**Comment by san0suke** [comment]
Eu não achei nada na documentação dizendo que é possível fazer um checkout transparente de assinaturas. Estou entrando em contato com o pagseguro pra saber se é possível.

Provavelmente é possível desenvolver aquele checkout por Lightbox. Mas vou confirmar isso com eles e te respondo daí.

Quanto a adesão de planos: este plugin realiza diretamente assinaturas sem criação de planos, mas também acho que deve ser possível de desenvolver.

No momento eu estou em outro projeto, daqui a um mês e pouco acredito que estarei disponível.

**Comment by petrusdemelo** [comment]
Vou tentar implementar alguma coisa. Se conseguir com sucesso faço um pull request.

**Comment by san0suke** [comment]
Legal, se tiver alguma dúvida pode perguntar.

**Comment by bubag3** [comment]
Olá amigo! Sobre a taxa de adesão, acha que seria possível a implementação? Eu não entendo muito de PHP, gostaria de contribuir mas não sei como :(

**Comment by san0suke** [comment]
Você pode contribuir fazendo um pull request.

- Em PGA_Planos.class.php adicione um campo para receber o valor da taxa de adesão
- Em PGA_Assinaturas.class.php adicione o valor desta taxa na variável $data da função registrar_assinatura(). Verifique a documentação pra saber qual é o nome do parâmetro que se deve passar.

**Comment by bubag3** [comment]
Obrigado pela resposta. Não sei como fazer isso que falou! Que tristeza hahaha

**Comment by Stormcloud** [comment]
Há uma documentação para pagamentos recorrentes transparentes:

**Comment by Stormcloud** [comment]
Há uma documentação para criar adesão à planos recorrentes em checkout transparente:

[Pagamento Recorrente Transparente](https://dev.pagseguro.uol.com.br/documentacao/pagamento-online/pagamentos/pagamento-recorrente-transparente)

**Comment by jonasrafael** [comment]
@san0suke fiz vários testes e colocamos uma demo no ar e realmente o checkout com o pagseguro normal tem muiiiito problema, sem contar que o site deles não fica nem responsivo na hora da conclusão do pagamento. 

Se você puder pegar essa missão, acho justo rolar uma doação!

**Comment by san0suke** [comment]
Não sei nem o que te dizer. Por um lado eu quero ajudar, mas por outro, assim como todos, não tenho tempo por que tenho por conta do trabalho.
