### ISSUE TITLE
Testando Plugin

### ISSUE THREAD

**Issue by rbarcelo** [san0suke/pagseguro-assinaturas-rcs#6]
Parabéns pela iniciativa!
Estou testando aqui e no final, na hora de fazer o pagamento na loja Woocomerce não vai para pagseguro.
Fica na propria loja mostrando uma página com o nome Pagar Pedido onde mostra o detalhe mais não vi para Pague seguro. 
![image](https://user-images.githubusercontent.com/11248471/28494377-f1a8e426-6f02-11e7-9540-03fb4e4ae947.png)

**Comment by san0suke** [comment]
Verifique se a pasta baixada está com o final -master e remova o "-master"

**Comment by rbarcelo** [comment]
Vou olhar, muito obrigado

De: san0suke [mailto:notifications@github.com]
Enviada em: sábado, 22 de julho de 2017 23:07
Para: san0suke/pagseguro-assinaturas-rcs <pagseguro-assinaturas-rcs@noreply.github.com>
Cc: rbarcelo <rbarcelo@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [san0suke/pagseguro-assinaturas-rcs] Testando Plugin (#6)


Verifique se a pasta baixada está com o final -master e remova o "-master"

**Comment by rbarcelo** [comment]
Funcionou!!! Muito obrigado!!!


De: san0suke [mailto:notifications@github.com]
Enviada em: sábado, 22 de julho de 2017 23:07
Para: san0suke/pagseguro-assinaturas-rcs <pagseguro-assinaturas-rcs@noreply.github.com>
Cc: rbarcelo <rbarcelo@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [san0suke/pagseguro-assinaturas-rcs] Testando Plugin (#6)


Verifique se a pasta baixada está com o final -master e remova o "-master"

**Comment by rbarcelo** [comment]
Olá san0suke, o plugin funcionou perfeito depois de tirar o -master no final da pasta. Testei no sandbox e tudo sem problema.  Estou agora quebrando cabeça com a posiblidade de oferecer assinaturas personalizadas. No sentido de poder acrescentar variações de produto  na assinatura. 
Mais no próprio Woocomerce na hora que marco esta opção de produto variavel. Já não oferece mais a opção de assinatura. Nem mesmo dentro das variáveis do produto.  Por exemplo preciso que o clinet escolha entre duas opções de assinatura para criança de 0-3anos |4-6anos |7-9 anos. Se tem ou não irmão e a idade do irmão. Para saber que produto enviar cada mês.
Alguma sugestão? Muito Obrigado
