### ISSUE TITLE
Não redireciona para o pagseguro

### ISSUE THREAD

**Issue by lucasalbuquerque** [san0suke/pagseguro-assinaturas-rcs#7]
fala mano, blz? primeiramente valeu pela iniciantiva

cara, configurei tudo, mas ao finalziar checkout, ele me mostra o resumo do pedido e não me redireciona para o pagseguro.. 

token do sandbox e do pagseguro adicionados, email também, plano criado, plugin ativo. o que pode ser?

**Comment by san0suke** [comment]
Verifique se a pasta foi baixada com o sufixo "-master" e remova.

**Comment by lucasalbuquerque** [comment]
exclui, removi o sufixo, subi de novo, e nada. :(

**Comment by san0suke** [comment]
Geralmente são arquivos javascript que não estão sendo incluídos com sucesso. 
Mas podem ser outras coisas, lembre-se que os produtos possuem valor mínimo, informe mais ou menos 2 reais no mínimo.
Confirma pra mim se os javascript estão sendo ou não excluídos.

**Comment by lucasalbuquerque** [comment]
Foi, jquery estava em conflito. 

Uma última coisa, ele tem um delay de uns 8 segundos para aparecer que esta processando o pagamento, tem como diminuir isso?

**Comment by san0suke** [comment]
Então... a página tem que carregar né... o script começa a executar logo após o carregamento da página.

Se tiver alguma idéia para reduzir este tempo, faça um pullrequest no arquivo:
js/checkout.js
