### ISSUE TITLE
O plugin só trabalha com produtos simples no woocomerce.

### ISSUE THREAD

**Issue by rbarcelo** [san0suke/pagseguro-assinaturas-rcs#8]
Olá san0suke, o plugin funcionou perfeito depois de tirar o -master no final da pasta. Testei no sandbox e tudo sem problema. Estou agora quebrando cabeça com a possiblidade de oferecer assinaturas personalizadas. No sentido de poder acrescentar variações de produto na assinatura.
Mais no próprio Woocomerce na hora que marco esta opção de produto variável. Já não oferece mais a opção de assinatura. Nem mesmo dentro das variáveis do produto. Por exemplo preciso que o clinete escolha entre duas opções de assinatura para criança de 0-3anos |4-6anos |7-9 anos. Se tem ou não irmão e a idade do irmão. Para saber que produto enviar cada mês.
Alguma sugestão? Muito Obrigado

**Comment by san0suke** [comment]
Crie um produto para cada tipo de assinatura

**Comment by rbarcelo** [comment]
Sim, eu tenho 3 tipos de assinaturas, é um clube para leitura infantil. A ideia  é que a pessoa escolha se deseja receber 1 livro por mês, 2 livros por mês ou 3 livros por mês. Na hora de escolher o plano de assinatura. Desejava que o cliente informe a idade da criança tipo menu drop down. com as variáveis que mencionei antes. Etc. 
Por exemplo acho que seria interessante a opção de produtos variáveis por assinatura por exemplo no caso de pacotes customizáveis de hosting. Onde você precisa escolher Quantidade de memória ram, tipo de hdd ou ssd, etc. 
O plugin está ôtimo e no sandbox funcionou certinho. Vou tentar resolver esta necessidade com a "notas do pedido no checkout"
Muito obrigado. Ramiro.
